Repository hearth-rs/hearth, pull requests merged in 2024-01, with the labels that each got.

#280 terminal: don't skip drawing foregrounds of 'full' cells
  plugins/terminal/src/terminal.rs
Labels: bug, host

#274 Route process logs through tracing
  core/runtime/src/process.rs
  core/runtime/src/runtime.rs
  core/runtime/src/utils.rs
  core/schema/Cargo.toml
  core/schema/src/lib.rs
  guest/rust/Cargo.toml
  guest/rust/hearth-guest/Cargo.toml
  guest/rust/hearth-guest/src/lib.rs
  guest/rust/hearth-guest/src/subscriber.rs
  kindling/Cargo.toml
  kindling/host/Cargo.toml
  kindling/host/src/lib.rs
  kindling/services/window-test/src/lib.rs
  plugins/canvas/src/lib.rs
  plugins/init/src/lib.rs
  plugins/wasm/src/lib.rs
Labels: enhancement, guest, host

#287 Add `GetProcessMetadata` trait and derive macro
  core/macros/src/lib.rs
  core/runtime/Cargo.toml
  core/runtime/src/lib.rs
  core/runtime/src/utils.rs
  main/client/src/window.rs
  plugins/canvas/src/lib.rs
  plugins/debug-draw/src/lib.rs
  plugins/fs/src/lib.rs
  plugins/renderer/src/lib.rs
  plugins/terminal/src/lib.rs
  plugins/time/src/lib.rs
  plugins/wasm/src/lib.rs
Labels: enhancement, host, complex

#290 runtime: fix spawn future
  core/runtime/src/utils.rs
Labels: bug, host

#294 Add kindling-schema crate
  kindling/Cargo.toml
  kindling/schema/Cargo.toml
  kindling/schema/src/lib.rs
  kindling/utils/src/registry.rs
Labels: guest, easy

#296 Purge config code
  core/runtime/src/runtime.rs
  main/client/src/main.rs
  main/server/src/main.rs
  plugins/wasm/examples/run_wasm.rs
Labels: host, easy

#299 kindling: remove window-test
  kindling/services/window-test/Cargo.toml
  kindling/services/window-test/src/lib.rs
Labels: guest, easy
